name: Azure CI-CD
on: 
  push:
    branches: [ azure ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Use Node.js
      uses: actions/setup-node@v2
      with: 
        node-version: '16.x'

    - uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install
    
    - name: lint
      run: npm run lint
    
    - name: Unit tests
      run: npm run test:ci
    
  build: 
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js
      uses: actions/setup-node@v2
      with: 
        node-version: '16.x'

    - uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install
      
    - name: Build app
      run: npm run build:prod
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with: 
        name: devops-test-${{ github.run_id }}-${{ github.run_number }}
        path: ./dist/devops-test

  deploy: 
    needs: build
    runs-on: ubuntu-latest

    steps: 
    - name: Dowload artifact
      uses: actions/download-artifact@v2
      with: 
        name: devops-test-${{ github.run_id }}-${{ github.run_number }} 
        path: './build'

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AZURE_HOST }}
        username: ${{ secrets.AZURE_USERNAME }}
        key: ${{ secrets.AZURE_SSHKEY }}
        script: ls

    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.AZURE_HOST }}
        username: ${{ secrets.AZURE_USERNAME }}
        key: ${{ secrets.AZURE_SSHKEY }}
        source: './build/'
        target: '/var/www/'
    